# -*- coding: utf-8 -*-
"""webscrapping_assignment1_lisa mbwia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQFaQA3mOxY9jTFcCj3q5diuI0H7Unf8
"""

!pip install requests

pip install BeautifulSoup4

from bs4 import BeautifulSoup
import requests
#Webscrape papers for research
url = 'https://www.lisambwia.com/'
reponse  = requests.get(url)
soup = BeautifulSoup(reponse.text,'html.parser')

print(soup)

print(soup.prettify())

print(soup.title.text) # Title

print(soup.a.prettify())# HTML

print(soup.p.text) # Paragraph

print(soup.img.prettify()) #Image

print(soup.style.text) #Style

print(soup.style.prettify())#Style